esapi/api.search.go, esapi/esapi.go, esapi/esapi_integration_test.go, esapi/esapi_internal_test.go
As reported in #25 and #35, the current conversion of `time.Duration` into an Elasticsearch [time unit](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units) is broken.
This patch builds on the implementation and discussion in #27, and adds a `esapi.formatDuration()` unexported helper function to be used in the generated code.
=> Fix `time.Duration` conversion to Elasticsearch's time unit

esutil/doc.go, esutil/json_reader.go, esutil/json_reader_benchmark_test.go, esutil/json_reader_internal_test.go
This patch adds a `JSONReader()` helper method to facilitate passing eg. a `map[string]string` as the body, without requiring the user to manually encode it into JSON and create eg. a `strings.Reader`:
```golang
res, err = es.Search(
es.Search.WithIndex("test"),
es.Search.WithBody(esutil.JSONReader(map[string]string{"query": {"match": {"title": "test"}}})),
)
```
The package defines the `JSONEncoder` interface, so it's possible for the outside code to provide
an object implementing it, in order to use eg. a third-party JSON package. The default encoder
is "encoding/json".
(Related: https://github.com/elastic/go-elasticsearch/issues/42)
=> Add the JSONReader helper

estransport/connection.go, estransport/estransport.go, estransport/metrics.go
These fields are redundant, as you can check that metrics is non-nil.
=> estransport: remove enableMetrics

doc.go, elasticsearch.go, elasticsearch_internal_test.go
To prevent issues reported in #113, when the addresses are set in configuration — either via `cfg.Addresses` or `cfg.CloudID` —, ignore the `ELASTICSEARCH_URL` variable.
=> Ignore the ELASTICSEARCH_URL variable when address is passed in configuration

README.md
This is a minor change to the readme file that adds a missing res.Body.Close().
=> [README] Add missing res.Body.Close()

.github/workflows/test-unit-tip.yml
Move to new syntax: https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files
=> move away from set-env in test-unit-tip workflow

.doc/installation.asciidoc, .doc/overview.asciidoc
This PR adds a `Features` subsection to the `Overview` that contains a bulleted list of client features.
It also moves the compatibility matrix from `Overview` to `Installation`.
[GO Overview](https://go-elasticsearch_195.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/overview.html)
=> [DOCS] Adds Features subsection to Overview

elasticsearch.go, estransport/discovery.go, estransport/estransport.go, estransport/estransport_internal_test.go, estransport/logger_internal_test.go, estransport/metaheader.go, estransport/metaheader_test.go, esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
* Transport: Add x-elastic-meta-header to Go client transport and discovery
Util: Add x-elastic-meta-header usage in bulk indexer helper
* Transport: Tests: Enhance precision of expected header value
* Transport: Add Http Client identifier to meta header
=> Implement the X-Elastic-Client-Meta HTTP header (#236)

estransport/estransport.go, estransport/estransport_integration_test.go, estransport/estransport_internal_test.go
This fixes the offset by one problem in the current retry loop handling.
MaxRetries should reflect the number of retries the client intends to do after the initial request up to the overall timeout. 
Closes #233
=> Transport: MaxRetries mechanism starts after initial request

_examples/xkcdsearch/Dockerfile
xcdsearch example: Dockerfile path to xkcd in _examples/xcdsearch was wrong
=> Fixed invalid xcdsearch path to xkcd in _examples/xcdsearch Dockerfile

estransport/discovery.go
There are no  error prone cases in getNodeURL.
So the second returning parameter looks redundant.
=> Transport: remove redundant error in return from getNodeURL

internal/build/cmd/generate/commands/gensource/generator.go, internal/build/cmd/generate/commands/gensource/model.go
Whenever an endpoint has both GET and POST method available
favor the POST method to avoid leaking goroutine as documented in #250. 
This change impacts the following APIs :
* EqlSearch
* GraphExplore
* IndicesReloadSearchAnalyzers
* MLGetBuckets
* MLGetCalendars
* MLGetCategories
* MLGetInfluencers
* MLGetModelSnapshots
* MLGetOverallBuckets
* MLGetRecords
* MLPreviewDatafeed
* RollupRollupSearch
* SecurityHasPrivileges
* WatcherQueryWatches
=> Favor POST method if GET and POST are available

estransport/discovery.go, estransport/discovery_internal_test.go, estransport/testdata/nodes.info.json
Refactor the way the nodes are selected in discovery.
Only master nodes should be filtered out.
This addresses the issue #256
=> Discovery should filter master only nodes

estransport/estransport.go, estransport/estransport_internal_test.go
In Elasticsearch 7.13 will be introduced a new compatibility header in the following form:
```
Accept:       application/vnd.elasticsearch+json;compatible-with=7
Content-Type: application/vnd.elasticsearch+json; compatible-with=7
```
This allows the progressive migration from `7.x` to `8.x` as Elasticsearch should be upgraded first after the compatibility header is configured and clients should be upgraded second.
This compatibility header can be enabled by setting the `ELASTIC_CLIENT_APIVERSIONING` to `true` or by passing the before mentioned headers in the request.
=> Add support for HTTP  API compatibility header

.doc/connecting.asciidoc, .doc/index.asciidoc
This PR adds a `Connecting` section to the Go Clients docs.
[Connecting](https://go-elasticsearch_287.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/connecting.html)
=> [DOCS] Adds Connecting section to Go docs

elasticsearch.go, estransport/estransport.go, estransport/estransport_internal_test.go
Elasticsearch is able to accept *gzip*-compressed request bodies, but currently this library has no functionality to send compressed request bodies.
Request compression can be important in e.g. the situation where you are pushing a lot of data out from a cloud provider to a self-hosted Elasticsearch instance, and being billed heavily for bandwidth. Issue https://github.com/elastic/go-elasticsearch/issues/217 requests this feature.
This PR adds a client flag `CompressRequestBody` which, if enabled, causes request bodies to be compressed. The flag is disabled by default. Also added a couple of tests for the feature.
=> Add option to enable gzip compression on request bodies

elasticsearch.go, elasticsearch_internal_test.go
- perform cheaper bool checks before synchronisation methods
- don't issue original request if product check fails
- check original request error before response header check (avoiding panic)
- replace `sync.Once` approach so transient network errors are not cached
=> Product check fixes

elasticsearch.go, elasticsearch_internal_test.go
* Product check improvements
- don't issue original request if product check fails
- check original request error before response header check
(avoiding panic)
* Don't cache product check errors
The product check could have failed because
of a transient network error, so repeat the
check on subsequent requests as long as there
has not been a prior success.
=> Product check fixes (#303)

elasticsearch.go, elasticsearch_internal_test.go, esapi/esapi_benchmark_test.go
This ensures the product check is not flagged wrongfully as successful if the answer has not been properly validated.
The client will retry product check until success or error.
=> Product check: Improve retry mechanism 

elasticsearch.go, elasticsearch_internal_test.go, esapi/esapi_benchmark_test.go
Handling HTTP errors
Handling special cases for 401 and 403 on Info
Handling non-default build flavor
=> Backport to 7.14 the latest product check update

estransport/estransport.go, estransport/estransport_internal_test.go
Abort retrying when the request context has been cancelled.
Fixes https://github.com/elastic/go-elasticsearch/issues/300
=> estransport: honour request context cancellation

internal/build/cmd/generate/commands/gensource/generator.go
This allows the integer parameters found in `search_mvt` to be handled correctly.
=> Generator: Add integer url parameters handling

estransport/estransport.go, estransport/estransport_internal_test.go
Backport to 7.x of https://github.com/elastic/go-elasticsearch/pull/335
=> Allow to overwrite User-Agent http request header (#335)

_benchmarks/benchmarks/cmd/main.go, _benchmarks/benchmarks/go.mod, elasticsearch.go, go.mod, go.sum
This pull request integrates the latest version of the `elastic-transport-go` package.
It introduces a new callback `RetryOnError` which allows the user to decide which errors should be retried and replaces the old `RetryOnTimeout`.
For context this function gets the `*http.Request` as well as the matching `error`.
=> [Transport]Update transport with resilient retry

internal/build/cmd/generate/commands/gentests/skips.go
search_mvt uses `x,y` coordinates as key which are translated by the yaml parser to `x,true`
skipping these until a compliant solution is found.
=> Add incompatible yaml tests to skip list

internal/build/cmd/generate/commands/gentests/skips.go
* Add incompatible yaml tests to skip list
* Update skip lists with wrongly identified list instead of maps
=> [Backport 8.0] Add incompatible yaml tests to skip list (#398)

internal/build/cmd/generate/commands/gensource/generator.go, internal/build/cmd/generate/commands/gentests/skips.go
This PR addresses the fact that required arguments that can be pointers shouldn't be passed as nil.
It aligns with the behavior of other clients and partly addresses #201
=> [Generator] Required arguments pointers shouldn't be nil

elasticsearch.go, elasticsearch_internal_test.go
This right the wrongs and adds a test case to reflect this and prevent mistakes in the future.
=> Compatibility header should not set content-type when body is nil

elasticsearch.go, elasticsearch_internal_test.go
* Only send content-type compatibility header if body is present
* Add test to check for content-type in case of an empty body
=> [Backport 8.0] Compatibility header should not set content-type when body is nil (#406)

esapi/esapi_request_internal_test.go, internal/build/cmd/generate/commands/gensource/generator.go
This PR fixes #201 by adding a scheme to build a viable url.
It prevents the `url.Parse` to trip up during the `http.NewRequest` call.
The then created `req.Scheme` and `req.Host` will be overridden by the `elastictransport.Do` via the `setReqUrl` method upon request execution.
=> Add basic scheme to url building path to prevent mishaps in parsing

_examples/cloudfunction/function_test.go, _examples/extension/main.go, _examples/instrumentation/expvar.go, _examples/logging/custom.go, _examples/logging/default.go, _examples/security/tls_configure_ca.go, _examples/security/tls_with_ca.go, _examples/xkcdsearch/store_test.go, elasticsearch_benchmark_test.go, elasticsearch_example_test.go, elasticsearch_integration_test.go, esapi/esapi_benchmark_test.go, esapi/esapi_integration_test.go, esapi/esapi_internal_test.go, esapi/esapi_response_internal_test.go, esutil/bulk_indexer_benchmark_test.go, esutil/bulk_indexer_example_test.go, esutil/bulk_indexer_integration_test.go, esutil/bulk_indexer_internal_test.go, esutil/json_reader_benchmark_test.go, esutil/json_reader_integration_test.go, esutil/json_reader_internal_test.go, internal/build/cmd/generate/commands/gensource/model.go, internal/build/cmd/generate/commands/genstruct/command.go, internal/build/cmd/generate/commands/gentests/gen_api_registry.go, internal/build/cmd/tools/commands/spec/command.go, internal/build/cmd/tools/commands/spec/command_test.go
Reformat the project with the standard `gofmt` tool
Add `go:build` tags.
=> Reformat existing Go code

_examples/cloudfunction/function_test.go, _examples/extension/main.go, _examples/instrumentation/expvar.go, _examples/logging/custom.go, _examples/logging/default.go, _examples/security/tls_configure_ca.go, _examples/security/tls_with_ca.go, _examples/xkcdsearch/store_test.go, elasticsearch_benchmark_test.go, elasticsearch_example_test.go, elasticsearch_integration_test.go, esapi/esapi_benchmark_test.go, esapi/esapi_integration_test.go, esapi/esapi_internal_test.go, esapi/esapi_response_internal_test.go, esutil/bulk_indexer_benchmark_test.go, esutil/bulk_indexer_example_test.go, esutil/bulk_indexer_integration_test.go, esutil/bulk_indexer_internal_test.go, esutil/json_reader_benchmark_test.go, esutil/json_reader_integration_test.go, esutil/json_reader_internal_test.go, internal/build/cmd/generate/commands/gensource/model.go, internal/build/cmd/generate/commands/genstruct/command.go, internal/build/cmd/generate/commands/gentests/gen_api_registry.go, internal/build/cmd/tools/commands/spec/command.go, internal/build/cmd/tools/commands/spec/command_test.go
Reformat the project with the standard gofmt tool
Add go:build tags.
=> Reformat existing Go code, add build tags

_examples/xkcdsearch/web/index.html
=> [Examples] Fix vue dependancy in xkcdsearch index html

elasticsearch_internal_test.go
Use Elasticsearch test certificate to validate fingerprinting in unit test.
=> [CI] Update testserver fingerprint

README.md
`programatically` → `programmatically`
`adresses` → `addresses`
=> Fixes typos in README.md

.ci/Dockerfile
=> [Backport 7.17] CI: Use Go install to bootstrap test tools in Dockerfile

.ci/Dockerfile
=> [Backport 8.1] CI: Use Go install to bootstrap test tools in Dockerfile

esutil/bulk_indexer.go
Relate Issue: https://github.com/elastic/go-elasticsearch/issues/461
On bulk update action, support retryonconflict field in 5.x, 6.x, 7.x.
=> support retry in bulk update

.doc/connecting.asciidoc, README.md
This PR revamps the connecting section of the documentation and adds relevant examples on how to connect, use TLS and authenticate a client on different cluster layouts.
=> Add security on by default documentation

README.md
Just took a look after being a long time user of oliver/elastic-go and noticed a quite jarring promotion of string concatenation in the example for indexing a document.
I don't think a database driver should be promoting usage of string concatenation. Someone is going to copy this into production and end up with an injection vulnerability or request smuggling issue.
https://github.com/elastic/go-elasticsearch#usage
=> replace readme string concat with json marshal

README.md
=> [Backport 7.17] use struct in readme instead of string buffer

.doc/overview.asciidoc
The [README.md](https://github.com/elastic/go-elasticsearch#readme) is already updated, but [Elastic Docs](https://www.elastic.co/guide/en/elasticsearch/client/go-api/master/overview.html) isn't.
=> Use pkg.go.dev instead of godoc.org on overview page

esutil/bulk_indexer.go, esutil/bulk_indexer_integration_test.go, esutil/bulk_indexer_internal_test.go
This PR addresses the issue #557 which leads to abnormal memory consumption in burst cases within the indexer's workers.
=> [BulkIndexer] reduce memory consumption

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
Follow up to https://github.com/elastic/go-elasticsearch/pull/558
=> [BulkIndexer] Improve memory consumption for length calculation

esutil/bulk_indexer.go
My client application writes a lot of relatively small documents (few hundred bytes each) into ES. Without request compression, the bulk indexer is responsible for >90% of the CPU spent by the client. With request compression it is less, as ~20% of the CPU time is now spent inside the gzip compression. It still seemed worth improving the the bulk indexer code...
The application writes ~3 million documents to a remote ES cluster.
```
real    4m43.854s
user    5m41.925s
sys     0m23.021s
(pprof) Duration: 283.71s, Total samples = 360.56s (127.09%)
```
```
real    4m44.704s
user    5m4.591s
sys     0m20.914s
(pprof) Duration: 284.55s, Total samples = 322.17s (113.22%)
```
```
real    4m41.193s
user    4m42.874s
sys     0m19.013s
(pprof) Duration: 281.10s, Total samples = 298.95s (106.35%) …
```
=> Reduce CPU usage

esutil/bulk_indexer.go
* Compute length using Seek()
* Reduce heap allocations in marshallMeta
* Remove outdated comment
Co-authored-by: Laurent Saint-Félix <laurent.saintfelix@elastic.co>
=> [Backport 8.6] Reduce CPU usage (#575)

elasticsearch.go, esutil/bulk_indexer_integration_test.go, go.mod, go.sum, internal/build/go.sum
**Disclaimer**: This PR depends on https://github.com/elastic/elastic-transport-go/pull/12 to be merged.
**Story / Background**
With our large number of documents to be created, enabling the request compression
gives us ~15-20x less payload to be transferred from client to ES which translates
into ~4-5x faster wall time for the whole operation.
Of course, the latter is heavily dependent on the network speed between client and ES.
Example timings from `time` (somewhat flaky)
```
real    0m5.496s
user    0m0.903s
sys     0m0.150s
```
With compression enabled, the consumed user CPU time goes up.
Go pprof (sort=cum) shows 970ms
```
flat  flat%   sum%        cum   cum%
20ms  2.06%  2.06%      460ms 47.42%  github.com/elastic/go-elasticsearch/v8/esutil.(*worker).flush
0     0%  2.06%      240ms …
```
=> Add Config.CompressRequestBodyLevel

.doc/connecting.asciidoc, .doc/index.asciidoc
Related to https://github.com/elastic/clients-team/issues/532.
This PR adds a reference of `source_branch` to the index file and changes two URLs to use `{branch}` instead of `master`.
=> [DOCS] References source_branch in index and changes URLs

.doc/connecting.asciidoc, .doc/index.asciidoc
Backports the following changes to the 8.3 branch:
[DOCS] References source_branch in index and changes URLs #599
=> [8.3][DOCS] References source_branch in index and changes URLs (#599)

.doc/connecting.asciidoc, .doc/index.asciidoc
Backports the following changes to the 8.4 branch:
[DOCS] References source_branch in index and changes URLs #599
=> [8.4][DOCS] References source_branch in index and changes URLs (#599)

.doc/connecting.asciidoc, .doc/index.asciidoc
Backports the following changes to the 8.7 branch:
[DOCS] References source_branch in index and changes URLs #599
=> [8.7][DOCS] References source_branch in index and changes URLs (#599)

esapi/esapi.response_example_test.go
This adds `3xx` to the `Response.IsError()` example comment as  [it catches `>299` status codes](https://github.com/elastic/go-elasticsearch/blob/11608f98966a036fb555a51e7a08955f4d042c28/esapi/esapi.response.go#L89-L93).
=> Mention `Response.IsError()` also handles 3xx in example

esutil/bulk_indexer.go
Bulk Indexer: In run() we drop the current item when the flush() failed.
This PR fixes it.
=> Do not drop item after flush() failed

esutil/bulk_indexer.go
=> [Backport 8.7] Do not drop item after flush() failed

.doc/index-custom-title-page.html
This PR adds a new landing page to the Go client book so it will be more in line with the [main docs landing page](https://www.elastic.co/guide/index.html), the [ES guide landing page](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html), and the [Kibana guide landing page](https://www.elastic.co/guide/en/kibana/current/index.html).
* [Current Go docs landing page](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/index.html)
* [New Go docs landing page proposed in this PR](https://go-elasticsearch_631.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/index.html)
The content can be easily modified based on feedback. There are restrictions on the use of the Go logo, so the hero image of the page doesn't contain it.
=> [DOCS] Creates custom landing page for the Go client book

go.mod, go.sum
* Transport: Bump to version 1a3c63d
=> [Backport 8.7] Bump transport version to 1a3c63d

.doc/index-custom-title-page.html
This PR:
* changes the hero image of the Go landing page to include the Go gopher,
* adds a licensing line about the mascot to the bottom of the page.
[Go landing page](https://go-elasticsearch_642.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/index.html)
=> [DOCS] Changes hero image on the landing page and adds a line about license

CHANGELOG.md
=> Changelog for 8.7.0 release

estransport/estransport.go, estransport/estransport_internal_test.go
transport builds an incorrect request path if the address is configured with a path, for example:
```
eCnf := elasticsearch.Config{
Addresses: []string{
"https://server.com/somepath"
},
}
``` 
it happens when retries is enabled and the API returns an error, transports adds to the request "/somepath" on each retry instead of building a new path.
=> Reties With not empty URL Path

.doc/index-custom-title-page.html
This PR changes the URL of the getting started button on the landing page.
=> [DOCS] Changes getting started button link on landing page

README.md
This PR adds links to the different sections of the README file that point to the corresponding section of the getting started page. This way only the getting started documentation needs to be maintained and it will be the source of truth.
=> [DOCS] Restructures the repo README

typedapi/types/float64.go
The current implementation of unmarshaling Float64s does not handle Infinity values. This can be tested by creating a Sum aggregate of two document attributes that are both "Max Float" values or "Negative Max Float" values. The current behavior is a bubbled up error from `strconv.ParseFloat(string(data), 64)` which cannot handle a value like `"+Infinity"`.
=> Unmarshal NaN and Infinite values correctly

.doc/index-custom-title-page.html
**Problem:** In https://github.com/elastic/docs/pull/2752, we updated the URL prefix (`welcome-to-elastic`) and name for the "Welcome to Elastic Docs" docs. However, we still have some stray links that use the old `/welcome-to-elastic` URL prefix
**Solution:** Updates an outdated link.
=> [DOCS] Fix `welcome-to-elastic` link

.doc/index-custom-title-page.html
This will backport the following commits from `main` to `8.10`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#718)](https://github.com/elastic/go-elasticsearch/pull/718)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [8.10] [DOCS] Fix `welcome-to-elastic` link (#718)

.doc/index-custom-title-page.html
This will backport the following commits from `main` to `8.9`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#718)](https://github.com/elastic/go-elasticsearch/pull/718)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [8.9] [DOCS] Fix `welcome-to-elastic` link (#718)

.doc/index-custom-title-page.html
This will backport the following commits from `main` to `8.7`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#718)](https://github.com/elastic/go-elasticsearch/pull/718)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [8.7] [DOCS] Fix `welcome-to-elastic` link (#718)

.doc/index-custom-title-page.html
This will backport the following commits from `main` to `8.8`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#718)](https://github.com/elastic/go-elasticsearch/pull/718)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [8.8] [DOCS] Fix `welcome-to-elastic` link (#718)

internal/build/utils/map.go
Preallocate memory for result of MapKeys and MapValues to avoid expensive reallocations and further GC actions.
=> utils/map: preallocate memory

.doc/getting-started.asciidoc
`{ query: { match_all: {} } }` response: 
```json
{
"error": {
"type": "x_content_parse_exception",
"caused_by": {
"type": "json_parse_exception",
"reason": "Unexpected character ('m' (code 109)): was expecting double-quote to start field name\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 15]"
}
},
"status": 400
}
```
=> Use double-quote to start field name

.doc/getting-started.asciidoc, .doc/tab-widgets/connecting-widget.asciidoc, .doc/tab-widgets/connecting.asciidoc, .doc/tab-widgets/create-index-widget.asciidoc, .doc/tab-widgets/create-index.asciidoc, .doc/tab-widgets/delete-documents-widget.asciidoc, .doc/tab-widgets/delete-documents.asciidoc, .doc/tab-widgets/delete-index-widget.asciidoc, .doc/tab-widgets/delete-index.asciidoc, .doc/tab-widgets/get-documents-widget.asciidoc, .doc/tab-widgets/get-documents.asciidoc, .doc/tab-widgets/index-document-widget.asciidoc, .doc/tab-widgets/index-document.asciidoc, .doc/tab-widgets/search-documents-widget.asciidoc, .doc/tab-widgets/search-documents.asciidoc, .doc/tab-widgets/update-documents-widget.asciidoc, .doc/tab-widgets/update-documents.asciidoc
This PR adds context selector widgets to the Getting started page. As the Go client utilizes two sets of APIs – low-level and fully-typed – it is useful to provide the possibility for the user to choose the context as it makes it easier to interpret the docs properly. The user's choice impacts all the widgets on the page; if they choose `fully-typed` in either of the widgets, the rest will also show the `fully-typed` tabs.
* [Getting started](https://go-elasticsearch_751.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/getting-started-go.html)
=> [DOCS] Adds context selector widget to the getting started page

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
The bulk indexer is missing the capability to set the `if_seq_no` and `if_primary_term` parameters. I added them here with a simple addition to the unit test for the writeMeta function. 
I ran into concurrency problems recently with Elasticsearch. I've built a work around in my own application that was experiencing a problem, but I would like to benefit from this feature in Elasticsearch to improve my own application. 
Hope this is helpful. Let me know if you need anything else from me!
ref: 
- https://www.elastic.co/guide/en/elasticsearch/reference/current/optimistic-concurrency-control.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-optimistic-concurrency-control
=> implement if_seq_no and if_primary_term parameters in bulk indexer item

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
=> [Backport 8.12] Add if_seq_no & if_primary_term to bulk indexer

esutil/bulk_indexer.go
Hello, I discovered that the [`time.Ticker`](https://pkg.go.dev/time#Ticker) instance within the [`BulkIndexer`](./esutil/bulk_indexer.go) is consuming a bunch of memory in my long running application that creates and closes many instances of the [`BulkIndexer`](./esutil/bulk_indexer.go). See the following screenshots of a [pprof heap visualization](https://pkg.go.dev/net/http/pprof) that I took of the application (forcing a garbage collection run too).
It appears that the [`time.Ticker`](https://pkg.go.dev/time#Ticker) instance is [`Reset`](https://pkg.go.dev/time#Ticker.Reset) within the `flush` method, thus causing the memory leak. The fix that I have tested and confirmed working is to simply call [`Stop`](https://pkg.go.dev/time#Ticker.Stop) on the ticker after the `flush` call since …
=> Fix ticker memory leak in bulk indexer due to internal flush call resetting the ticker

esutil/bulk_indexer.go
=> [Bakcport 8.12] Fix ticker memory leak in BulkIndexer

.doc/installation.asciidoc
This PR adds a compatibility matrix to the Introduction section of the Go book.
[Elasticsearch version compatibility](https://go-elasticsearch_bk_816.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/installation.html#_elasticsearch_version_compatibility)
=> [DOCS] Adds compatibility matrix to docs

elasticsearch.go, esutil/bulk_indexer_integration_test.go
This is a follow up PR for https://github.com/elastic/elastic-transport-go/pull/19
---- 
Added `PoolCompressor` option into `elasticsearch.Config` and pass it into `elastictransport.Config`.
=> add `PoolCompressor` option and propagate it to `elastictransport.Config`

CHANGELOG.md
Add a mention to the put_synonym_rule fix: https://github.com/elastic/elasticsearch-specification/pull/2407
=> Add put_synonym_rule fix

.buildkite/Dockerfile, .ci/Dockerfile, .github/workflows/build.yml, Makefile
This effectively removes `golint` which is deprecated.
=> [Dependency] remove golint

.doc/index.asciidoc, .doc/typedapi/esql.asciidoc, .doc/typedapi/index.asciidoc
Adds an `esql.asciidoc` file that sets up a basic structure for the ES|QL documentation. Based on @szabosteve's Java client docs PR ([#789](https://github.com/elastic/elasticsearch-java/pull/789/files)).
@Anaethelion This needs expanding and tailoring for the Go client (it's really just placeholder text from the Java client docs). All feedback is welcome, especially because I'm still so new to Elastic and to the client docs.
[Preview](https://go-elasticsearch_bk_860.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/esql.html)
=> [DOCS] Add ES|QL doc structure

internal/build/cmd/generate/commands/genexamples/translator.go, internal/build/cmd/generate/commands/gentests/generator.go, internal/build/cmd/generate/commands/gentests/model.go
Underscore names are not Go convention. See report card here: https://goreportcard.com/report/github.com/elastic/go-elasticsearch#golint
Also simplifying some map lookups.
=> Update variable names to Go convention + Simplify map lookups

esutil/bulk_indexer.go
The wg Delta should generally be added before relevant go-routines are launched. Reference: https://pkg.go.dev/sync#WaitGroup.Add
This also aligns the code with our other uses of waitgroups.
Closes https://github.com/elastic/go-elasticsearch/issues/796.
=> Bulk indexer: Follow convention and increment waitgroup in loop before creating goroutines

elasticsearch.go
=> [Backport 7.17] Check error in BaseClient.Perform #922

elasticsearch.go
* Check error in BaseClient.Perform
The http.Resonse will be nil on errors, so return early.
Fixes #913
* revert reordering of imports
---------
=> [Backport 8.x] Check error in BaseClient.Perform (#922)

elasticsearch.go
* Check error in BaseClient.Perform
The http.Resonse will be nil on errors, so return early.
Fixes #913
* revert reordering of imports
---------
=> [Backport 8.15] Check error in BaseClient.Perform (#922)

elasticsearch.go
* Check error in BaseClient.Perform
The http.Resonse will be nil on errors, so return early.
Fixes #913
* revert reordering of imports
---------
=> [Backport 8.16] Check error in BaseClient.Perform (#922)

elasticsearch.go
* Check error in BaseClient.Perform
The http.Resonse will be nil on errors, so return early.
Fixes #913
* revert reordering of imports
---------
=> [Backport 8.17] Check error in BaseClient.Perform (#922)

esutil/bulk_indexer.go
This pull request exposes the amount of bytes flushed in total by the Bulk indexer.
I tested this change locally and it worked as expected.
=> Expose BulkIndexer total flushed bytes metric

esutil/bulk_indexer.go
=> [Backport 8.17] esutil: Add failure_store key to bulk response item (#948)

esutil/bulk_indexer.go
=> [Backport 8.x] esutil: Add failure_store key to bulk response item

docs/reference/connecting.md
Follow up to #960 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
=> [docs] Clean up cross-repo links

docs/reference/connecting.md
Fix external links that incorrectly use `.md` instead of `.html`.
=> [docs] Fix external links

elasticsearch.go, internal/build/cmd/generate/commands/gensource/generator.go
This adds a constructor for the `BaseClient` without an API attached.
Easing up usage by passing the client into the endpoints, allowing for a slimmer compiled binary.
=> Feat: Add constructor for baseclient

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
Now, when using a pre-declared `TypedClient`, a separate `Client` instance had to be created via `NewClient` to pass it to `BulkIndexerConfig`.
To improve usability, this change updates the type of `BulkIndexerConfig.Client` to `esapi.Transport`, allowing both `Client` and `TypedClient` to be passed directly.
=> esutil: Modify the `BulkIndexerConfig.Client` type to `esapi.Transport`

docs/reference/_getting_started_with_the_api.md
Fixes various syntax and rendering errors that might include:
* Fixing broken images
* Hardcoding book-level substitution values
* Fixing incorrectly closed blocks (admonitions, tab sets, code blocks, dropdowns etc.)
* Fixing poorly migrated complex tables
* Fixing poorly migrated lists
* Fixing poorly migrated tab sets
* Removing inline text formatting from directive titles where they won't be rendered (for example, inline `code` formatting in dropdown titles)
* Specifying if a version is trying to communicate if a feature was added, deprecated, or coming (for example, during migration `deprecated:[8.15.0]` became `[8.15.0]`, which doesn't give any information about _what_ happened in 8.15.0)
* Fixing nested dropdowns / definition lists
* Fixing poorly migrated footnotes
* Updating …
=> [docs] Fix various syntax and rendering errors

.buildkite/run-repository.sh, CHANGELOG.md, go.mod
=> [Changelog] 8.18.1
