estransport/connection.go
Refactor Next and Resurrect to share most of the code.
This fixes a bug whereby metrics would not have been updated when calling `Next`.
=> estransport: refactor Next/Resurrect

.doc/index.asciidoc, .doc/installation.asciidoc, .doc/overview.asciidoc
This PR:
* revises the overview section,
* adds an installation section.
[Table of Contents](https://go-elasticsearch_185.docs-preview.app.elstc.co/guide/en/elasticsearch/client/go-api/master/index.html)
=> [DOCS] Reorganizes Overview and Installation chapters

internal/cmd/generate/commands/gentests/generator.go
=> Generator: Tests: Remove all & hidden datastreams before each tests

elasticsearch.go, estransport/estransport.go, estransport/estransport_internal_test.go, estransport/logger_internal_test.go, esutil/bulk_indexer_internal_test.go
This adds the ability to use a service token for authenticating with elasticsearch.
- Closes #246
=> Add support for service token based authentication.

elasticsearch.go, estransport/estransport.go, estransport/estransport_internal_test.go, estransport/logger_internal_test.go, esutil/bulk_indexer_internal_test.go
* Add support for service token based authentication.
* Fix grow.
=> Add support for service token based authentication. (#247)

esapi/api._.go, esapi/api.cluster.get_settings.go, esapi/api.features.reset_features.go, esapi/api.fleet.global_checkpoints.go, esapi/api.ingest.geo_ip_stats.go, esapi/api.shutdown.delete_node.go, esapi/api.shutdown.get_node.go, esapi/api.shutdown.put_node.go, esapi/api.xpack.text_structure.find_structure.go, internal/build/cmd/generate/commands/gentests/skips.go, internal/build/utils/naming.go
=> API: Update api and skiplist

.github/workflows/test-api.yml, .github/workflows/test-integration.yml, Makefile
=> CI: Set target to 7.12-SNAPSHOT to target 7.12.1

.ci/test-matrix.yml, Makefile, internal/version/version.go
=> CI: Update CI to 7.13.0-SNAPSHOT

internal/build/cmd/generate/commands/gensource/generator.go, internal/build/cmd/generate/commands/gensource/model.go
Whenever possible favor POST method if GET and POST are available
=> [BACKPORT 7.x] Generator: Favor POST method

estransport/estransport.go, estransport/estransport_internal_test.go
* Transport: Add compatibility header
=> [Backport 7.x] Add support for HTTP  API compatibility header

estransport/estransport.go, estransport/estransport_internal_test.go
* Transport: Add compatibility header
=> [Backport 7.13] Add support for HTTP  API compatibility header

internal/build/cmd/generate/commands/gensource/model.go
This changes ensures the arguments for methods are sorted before generating code.
=> Generator: Sort method arguments alphabetically

.doc/connecting.asciidoc, .doc/index.asciidoc
This PR backports the changes of the following commits to the 7.x branch:
[DOCS] Adds Connecting section to Go docs #287
=> [7.x][DOCS] Adds Connecting section to Go docs

estransport/estransport_integration_test.go, esutil/bulk_indexer_integration_test.go
Following #288 
Adds integration tests for transport and bulkindexer.
=> Add integration tests using compression

elasticsearch.go, estransport/estransport.go, estransport/estransport_integration_test.go, estransport/estransport_internal_test.go, esutil/bulk_indexer_integration_test.go
=> Backport on 7.x request body compression

internal/build/cmd/generate/commands/gentests/generator.go, internal/build/cmd/generate/commands/gentests/skips.go
Added cleanup phase before each test to handle presence of existing snapshots.
=> Add snapshot handling in test cases

elasticsearch.go, elasticsearch_internal_test.go, esapi/esapi_benchmark_test.go
=> Rework product check according to latest spec

estransport/estransport.go, estransport/estransport_internal_test.go
Co-authored-by: Laurent Saint-Félix <laurent.saintfelix@elastic.co>
=> [Backport 7.x] estransport: honour request context cancellation (#301)

internal/build/cmd/generate/commands/gensource/generator.go
=> Generator: handle long type for parameters

elasticsearch.go
This is important for ensuring request cancellation, as well as for tracing product check requests.
=> Thread request context through to product check

.doc/installation.asciidoc, README.md, _examples/cloudfunction/function_test.go, _examples/xkcdsearch/store_test.go, elasticsearch.go, elasticsearch_benchmark_test.go, elasticsearch_internal_test.go, esapi/esapi_benchmark_test.go, esutil/bulk_indexer_internal_test.go
This checks for the presence of the `X-Elastic-Product` in the first response from Elasticsearch.
=> Add product check for 8.x

.doc/installation.asciidoc, README.md
=> [Backport 7.14] Update compatibility matrix to reflect supported versions

.doc/installation.asciidoc, README.md
=> [Backport 7.x] Update compatibility matrix to reflect supported versions

.doc/installation.asciidoc, README.md
=> Update compatibility info

esapi/api._.go, esapi/api.indices.delete.go, esapi/api.nodes.clear_repositories_metering_archive.go, esapi/api.nodes.get_repositories_metering_info.go, esapi/api.xpack.open_point_in_time.go
=> API: Update APIs for Elasticsearch v7.15 (2c06575)

internal/build/cmd/generate/commands/gentests/generator.go, internal/build/cmd/generate/commands/gentests/model.go
Add arbitrary key replacement to integration tests
Add scientific float notation translation for date_range ES answer in integration tests
=> Improve integration test runner -- arbitrary key & date_range

.ci/run-elasticsearch.sh, esapi/api._.go, esapi/api.fleet.msearch.go, esapi/api.fleet.search.go, esapi/api.nodes.hot_threads.go, esapi/api.xpack.cat.ml_datafeeds.go, esapi/api.xpack.cat.ml_jobs.go, esapi/api.xpack.ml.close_job.go, esapi/api.xpack.ml.delete_trained_model.go, esapi/api.xpack.ml.get_datafeed_stats.go, esapi/api.xpack.ml.get_datafeeds.go, esapi/api.xpack.ml.get_job_stats.go, esapi/api.xpack.ml.get_jobs.go, esapi/api.xpack.ml.get_overall_buckets.go
=> Update api & CI spawn script

internal/build/cmd/generate/commands/gentests/generator.go, internal/build/cmd/generate/commands/gentests/model.go
This adds the replace mechanism for variables specified in yaml test runs.
=> CI: Integration, replace variable in payload

internal/build/cmd/generate/commands/gentests/generator.go, internal/build/cmd/generate/commands/gentests/model.go
=> Backport Integration: replace in payload

elasticsearch.go, elasticsearch_internal_test.go
=> [Client] Do not trigger product check on 401 or 403

esutil/bulk_indexer.go, esutil/bulk_indexer_integration_test.go, esutil/bulk_indexer_internal_test.go
=> [Backport] bulkdindexer version and routing

internal/build/cmd/generate/commands/gentests/skips.go
=> [Tests] Update skip list

elasticsearch.go, elasticsearch_internal_test.go
This PR reintegrates the compatibility header for 8.x with the external transport.
=> Client: Compatibility header with external transport

esutil/bulk_indexer.go
Allows to reuse the existing reader in callbacks without allocating a new buffer.
Should reduce memory footprint on large scale bulk indexers.
=> [BulkIndexer] Use ReadSeeker for BulkIndexerItem body

esutil/bulk_indexer.go
=> [Backport 8.0] Use ReadSeeker for BulkIndexerItem body

_benchmarks/benchmarks/cmd/main.go, _benchmarks/benchmarks/go.mod, elasticsearch.go, go.mod, go.sum
=> [Backport 8.0] Update transport to latest version with resilient retry (#385)

internal/build/cmd/generate/commands/gensource/generator.go, internal/build/cmd/generate/commands/gentests/skips.go
* Generator: add not nil validation for required arguments
* Skip: add empty required argument tests to skip list
=> [Generator] Required arguments pointers shouldn't be nil (#401)

esapi/esapi_request_internal_test.go, internal/build/cmd/generate/commands/gensource/generator.go
=> [Backport 8.0]Add basic scheme to url building path to prevent mishaps in parsing

internal/build/cmd/generate/commands/gentests/generator.go
Remove calendar, filters, transforms & trained models during xpack preflight
=> [Tests] Upgrade ML CI cleanup phase

internal/build/cmd/generate/commands/gentests/generator.go
=> [Backport 8.0] Remove calendar, filters, transforms & trained models during xpack preflight

esutil/bulk_indexer.go, esutil/bulk_indexer_integration_test.go
=> [Utils] Fix bulkindexer Routing field serialization

README.md, _examples/configuration.go, doc.go, elasticsearch_example_test.go, elasticsearch_integration_test.go
As suggested by @Gregory-Ledray
Fixes #318 
Closes #331
=> Upgrade TLS in documentation and examples

esutil/bulk_indexer.go
=> [Backport 8.2] support retry in bulk update

esutil/bulk_indexer.go
=> [Backport 7.17] support retry in bulk update

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
=> [BulkIndexer] Fix retry_on_conflict

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
line 533 will panic when assigned config.Header
=> fix concurrent map write error caused when assigned header

esutil/bulk_indexer.go, esutil/bulk_indexer_internal_test.go
=> [Backport 7.17] [BulkIndexer] fix concurrent map error caused when assigned header (#475)

esapi/api._.go, esapi/api.semantic_search.go, esapi/api.xpack.ml.update_trained_model_deployment.go, internal/build/cmd/generate/commands/gentests/model.go, internal/build/cmd/generate/commands/gentests/skips.go
Along with updates for yaml tests
=> [API] Update to 8.6.0

.doc/installation.asciidoc, .doc/typedapi/conventions/endpoints.asciidoc, .doc/typedapi/conventions/naming.asciidoc, .doc/typedapi/conventions/requests.asciidoc, .doc/typedapi/conventions/structure.asciidoc, .doc/typedapi/conventions/types.asciidoc, .doc/typedapi/examples/aggregations.asciidoc, .doc/typedapi/examples/indices.asciidoc, .doc/typedapi/examples/search.asciidoc, .doc/typedapi/queries.asciidoc
=> Update the documentation to remove the builder API

CHANGELOG.md
=> Add changelog for 8.5.0 release

elasticsearch_internal_test.go
=> [Test] Use error unwrapping in fingerprint unittest

esutil/bulk_indexer.go
=> Do not log nil error in bulk indexer

esutil/bulk_indexer.go
=> Do not log nil error in bulk indexer (#574)

esutil/bulk_indexer.go
* Compute length using Seek()
* Reduce heap allocations in marshallMeta
* Remove outdated comment
Co-authored-by: Laurent Saint-Félix <laurent.saintfelix@elastic.co>
=> [Backport 7.17] Reduce CPU usage (#575)

internal/build/cmd/generate/commands/gentests/model.go, internal/build/cmd/generate/commands/gentests/skips.go
=> [Backport] Update skip list 8.6

CHANGELOG.md
=> Add changelog for 8.6.0 release

README.md, _examples/main.go
=> Align code between readme and _examples

esutil/bulk_indexer.go, esutil/bulk_indexer_integration_test.go, esutil/bulk_indexer_internal_test.go
=> Revert inadequate backports #559 #565 #580

typedapi/typedclient.request.go
This PR update the interface following the changes implemented in #618
=> [TypedClient] Rename Request interface method following API changes

esapi/api._.go, esapi/api.health_report.go, esapi/api.xpack.ml.update_trained_model_deployment.go, esapi/api.xpack.transform.schedule_now_transform.go, esapi/api.xpack.transform.start_transform.go, internal/build/cmd/generate/commands/gentests/skips.go
=> [ESAPI] Update for 8.7

go.mod, go.sum
=> Transport: Bump to latest main version 1a3c63d

estransport/connection.go
Original https://github.com/elastic/elastic-transport-go/pull/16
=> [Backport 7.17] Prevent possibility of adding same connection multiple time to live pool

internal/build/cmd/generate/commands/gentests/model.go
=> Fixup #669: only serialize the map once

internal/build/cmd/generate/commands/gentests/skips.go
=> [CI] Update skip list with incompatible tests

CHANGELOG.md
=> Changelog: Add 8.9 release changelog

go.mod, go.sum
=> [Transport] pin version to v8.3.0

.doc/getting-started.asciidoc, .doc/tab-widgets/connecting-widget.asciidoc, .doc/tab-widgets/connecting.asciidoc, .doc/tab-widgets/create-index-widget.asciidoc, .doc/tab-widgets/create-index.asciidoc, .doc/tab-widgets/delete-documents-widget.asciidoc, .doc/tab-widgets/delete-documents.asciidoc, .doc/tab-widgets/delete-index-widget.asciidoc, .doc/tab-widgets/delete-index.asciidoc, .doc/tab-widgets/get-documents-widget.asciidoc, .doc/tab-widgets/get-documents.asciidoc, .doc/tab-widgets/index-document-widget.asciidoc, .doc/tab-widgets/index-document.asciidoc, .doc/tab-widgets/search-documents-widget.asciidoc, .doc/tab-widgets/search-documents.asciidoc, .doc/tab-widgets/update-documents-widget.asciidoc, .doc/tab-widgets/update-documents.asciidoc
This PR backports the following changes to the 8.11 branch:
https://github.com/elastic/go-elasticsearch/pull/751
=> [8.11][DOCS] Adds context selector widget to the getting started page

CHANGELOG.md
=> Update changelog for 8.12.0

.doc/connecting.asciidoc, .doc/typedapi/examples/indexing.asciidoc
=> [Backport 8.12] Backport documentation fixes to 8.12

typedapi/types/arraycomparecondition.go, typedapi/types/datedecayfunction.go, typedapi/types/geoboundingboxquery.go, typedapi/types/geodecayfunction.go, typedapi/types/geodistancequery.go, typedapi/types/geodistancesort.go, typedapi/types/geopolygonquery.go, typedapi/types/geoshapequery.go, typedapi/types/numericdecayfunction.go, typedapi/types/shapequery.go, typedapi/types/shardstore.go, typedapi/types/sortoptions.go, typedapi/types/termsquery.go
=> [Backport 8.13] TypedAPI: Fix additionalproperty ser/de

CHANGELOG.md
=> [Chanelog] Add changelog for 8.13.0

.doc/tab-widgets/index-document.asciidoc
=> [Backport 8.14] Update index-document.asciidoc (#851)

internal/build/cmd/generate/commands/gensource/generator.go
=> create_service_token should use POST is name is empty

.doc/index.asciidoc, .doc/typedapi/esql.asciidoc, .doc/typedapi/index.asciidoc
=> [Backport 8.14] Add ES|QL documentation

_examples/bulk/benchmarks/go.mod, _examples/bulk/go.mod, _examples/bulk/kafka/go.mod, _examples/cloudfunction/go.mod, _examples/encoding/go.mod, _examples/extension/go.mod, _examples/fasthttp/go.mod, _examples/go.mod, _examples/instrumentation/go.mod, _examples/logging/go.mod, _examples/security/go.mod, _examples/xkcdsearch/go.mod, go.mod, internal/build/go.mod, internal/testing/go.mod
=> Replace go version with toolchain in go.mod files

internal/build/cmd/generate/commands/gentests/model.go, internal/build/utils/metadata.go
Improves the Go scorecard from here: https://goreportcard.com/report/github.com/elastic/go-elasticsearch#golint
=> Refactor to outdent if/else blocks with return statements

esapi/test/go.mod, internal/build/go.mod
=> Bump go.mod toolchain to 1.22.0

esutil/bulk_indexer.go
=> [Backport 8.x] Expose BulkIndexer total flushed bytes metric (#914)

esutil/bulk_indexer.go
=> [Backport 8.15] Expose BulkIndexer total flushed bytes metric (#914)

esutil/bulk_indexer.go
=> [Backport 8.16] Expose BulkIndexer total flushed bytes metric (#914)

esutil/bulk_indexer.go
=> [Backport 8.18] esutil: Add failure_store key to bulk response item 

internal/build/cmd/generate/commands/gensource/command.go
=> Generator: exclude deprecated knn_search endpoint for v9
